/* Creating database DisasterAlleviationFoundation */
CREATE DATABASE DisasterAlleviationFoundation;

/* CREATING TABLE USERS */
CREATE TABLE USERS 
(
	USER_ID INT PRIMARY KEY IDENTITY NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(150) UNIQUE NOT NULL,
	PASSWORD VARCHAR(555) NOT NULL,
	ROLE VARCHAR(50) NOT NULL
);

/* CREATING TABLE FOR REPORTING DISASTERS */
CREATE TABLE DISASTER_REPORT
(
	DISASTER_REPORT_ID INT PRIMARY KEY IDENTITY NOT NULL,
	DISASTER_TYPE VARCHAR(250) NOT NULL,
	LOCATION VARCHAR(550) NOT NULL,
	DESCRIPTION VARCHAR(550) NOT NULL,
	DATE DATETIME NOT NULL,
	IMAGES VARBINARY(MAX),
	VIDEO VARBINARY(MAX),
	EMAIL VARCHAR(150) NOT NULL
);

/* CREATING TABLE FOR DONATION */
CREATE TABLE DONATION
(
	DONATION_ID INT PRIMARY KEY IDENTITY NOT NULL,
	DONATION_TYPE VARCHAR(50) NOT NULL,
	DONATION_AMOUNT MONEY NOT NULL,
	DESCRIPTION VARCHAR(550) NOT NULL,
	DONATED DATETIME NOT NULL,
	IMAGE VARBINARY(MAX),
	VIDEO VARBINARY(MAX),
	EMAIL VARCHAR(150) NOT NULL
	
);

/* CREATE TABLE FOR TASKS */
Create Table TASKS(
	TASK_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TASK_NAME VARCHAR(50) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(250),
	AREA_NAME VARCHAR(250),
	STATUS VARCHAR(50),
	EMAIL VARCHAR(150)  
);

/* CREATING TABLE FOR FOR VOLUNTEER SCHEDULES */
CREATE TABLE SCHEDULES(
	SCHEDULE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SCHEDULE_AREA VARCHAR(250) NOT NULL,
	SCHEDULE_TIME TIME NOT NULL,
	SCHEDULE_DATE DATE NOT NULL,
	STATUS VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(150)
);

/* CREATING TABLE FOR MESSAGES */
CREATE TABLE MESSAGE_VOLUNTEER(
	MESSAGE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EMAIL VARCHAR(150) FOREIGN KEY REFERENCES USERS(EMAIL),
	DESCRIPTION VARCHAR(2500) NOT NULL
);

/* CREATING TABLE FOR EMERGENCIESS */
CREATE TABLE Emergenciess(
	Emergencies_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	LOCATION VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	EMAIL VARCHAR(150) FOREIGN KEY REFERENCES USERS(EMAIL),
);

/* CREATING TABLE FOR FEEDBACKS */
CREATE TABLE feedBacks(
	FEEDBACK_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	EMAIL VARCHAR(150) FOREIGN KEY REFERENCES USERS(EMAIL),
);

/* VIEWING TABLE OUTPUT */
SELECT * FROM USERS;
SELECT * FROM DISASTER_REPORT
SELECT * FROM DONATION;
SELECT * FROM TASKS;
SELECT * FROM SCHEDULES;
SELECT * FROM MESSAGE_VOLUNTEER;
SELECT * FROM Emergenciess;
SELECT * FROM feedBacks;